<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/09/13 23:28:19
sfConfig::add(array(
  'mod_job_enabled' => true,
  'mod_job_view_class' => 'sfPHP',
  'mod_job_is_internal' => false,
));
