<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/09/13 23:31:29
sfConfig::add(array(
  'mod_default_enabled' => true,
  'mod_default_view_class' => 'sfPHP',
  'mod_default_is_internal' => false,
));
